# Generated by Django 3.2.6 on 2021-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата старта'),
        ),
    ]
