# Generated by Django 3.2.6 on 2021-10-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_alter_quiz_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestionresult',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
    ]
