# Generated by Django 3.2.7 on 2021-10-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20211019_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsToAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Вариант ответа')),
                ('isCorrect', models.BooleanField(verbose_name='Корректный ответ')),
            ],
        ),
    ]
