# Generated by Django 3.2.7 on 2021-10-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_optionstoanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options_to_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.optionstoanswer'),
        ),
    ]
