# Generated by Django 3.2.7 on 2021-10-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_question_options_to_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options_to_answer',
        ),
        migrations.AddField(
            model_name='optionstoanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='textAnswer',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='Ответ'),
        ),
    ]
